# TASK 1
dataset link : https://raw.githubusercontent.com/TirendazAcademy/PANDAS-TUTORIAL/main/DataSets/vgsalesGlobale.csv
#Exercise
Use the dataset of Game, we have explored earlier and perform following operations.

* Calculate the total global sales for all games in the dataset.
* Find the game with the highest global sales.
* Determine the average sales for each region (NA_Sales, EU_Sales, JP_Sales, Other_Sales).
* Find the top 5 most popular game genres based on global sales.
* Calculate the total sales for each genre in each region.
* Find the most popular genre in North America (NA_Sales).
* Display last 10 rows.
* Determine the top 3 gaming platforms with the highest global sales.
* Calculate the market share (percentage of global sales) for each genre.
* Calculate the correlation coefficient between NA_Sales and EU_Sales. (.corr function)

In [1]:
import pandas as pd

# Load the data into a DataFrame
df = pd.read_csv('vgsalesGlobale.csv')

#calculate the total global sales for the game 
total_sales = df['Global_Sales'].sum()
print("The total global sales for the game is: ", total_sales)

#Find the game with the highest global sales
highest_sales=df['Global_Sales'].max()
print("The game with the highest global sales is: ", highest_sales)

#avg sale of each region
NU = df['NA_Sales'].mean()
JP = df['JP_Sales'].mean()
EU = df['EU_Sales'].mean()

print("The average sales in North America is: ", NU)
print("The average sales in Japan is: ", JP)
print("The average sales in Europe is: ", EU)


# Find the top 5 most popular game genres based on global sales
pop_5 = df.groupby('Genre')['Global_Sales'].sum()
pop_5 = pop_5.sort_values(ascending=False).head(5)
print("The top 5 popular genres based on global sales are: ", pop_5)

#total sales for each genre for each region
total_sales_genre = df.groupby('Genre')[['NA_Sales', 'JP_Sales', 'EU_Sales']].sum()
print("The total sales for each genre for each region are: ", total_sales_genre)




The total global sales for the game is:  8920.44
The game with the highest global sales is:  82.74
The average sales in North America is:  0.26466742981082064
The average sales in Japan is:  0.077781660441017
The average sales in Europe is:  0.14665200626581515
The top 5 popular genres based on global sales are:  Genre
Action          1751.18
Sports          1330.93
Shooter         1037.37
Role-Playing     927.37
Platform         831.37
Name: Global_Sales, dtype: float64
The total sales for each genre for each region are:                NA_Sales  JP_Sales  EU_Sales
Genre                                     
Action          877.83    159.95    525.00
Adventure       105.80     52.07     64.13
Fighting        223.59     87.35    101.32
Misc            410.24    107.76    215.98
Platform        447.05    130.77    201.63
Puzzle          123.78     57.31     50.78
Racing          359.42     56.69    238.39
Role-Playing    327.28    352.31    188.06
Shooter         582.60     38.28    313.2

In [2]:
#pop genre in na
pop_NA  =total_sales_genre ['NA_Sales'].idxmax()
("The most popular genre in North America is: ", pop_NA)

#last 10 rows
last_10= df.tail(10)
display("The last 10 rows are: ", last_10)
#top3 platforms based on global sales
top_3 = df.groupby('Platform')['Global_Sales'].sum().sort_values(ascending=False).head(3)
display("The top 3 platforms based on global sales are: ", top_3)

#percentage of global sales for each genre
percent = df.groupby('Genre')['Global_Sales'].sum()
percent = percent/total_sales*100
display("The percentage of global sales for each genre is: ", percent)

#corrlation between NA_sales and EU_sales
cor = df['NA_Sales'].corr(df['EU_Sales'])
display("The correlation between NA_Sales and EU_Sales is: ", cor)


'The last 10 rows are: '

Rank                                               Name Platform  \
16588  16591                                   Mega Brain Boost       DS   
16589  16592  Chou Ezaru wa Akai Hana: Koi wa Tsuki ni Shiru...      PSV   
16590  16593  Eiyuu Densetsu: Sora no Kiseki Material Collec...      PSP   
16591  16594                                Myst IV: Revelation       PC   
16592  16595                                           Plushees       DS   
16593  16596                 Woody Woodpecker in Crazy Castle 5      GBA   
16594  16597                      Men in Black II: Alien Escape       GC   
16595  16598   SCORE International Baja 1000: The Official Game      PS2   
16596  16599                                         Know How 2       DS   
16597  16600                                   Spirits & Spells      GBA   

         Year         Genre              Publisher  NA_Sales  EU_Sales  \
16588  2008.0        Puzzle  Majesco Entertainment      0.01      0.00   
16589  2016.0        Action        dramatic create      0.00      0.00   
16590  2007.0  Role-Playing     Falcom Corporation      0.00      0.00   
16591  2004.0     Adventure                Ubisoft      0.01      0.00   
16592  2008.0    Simulation              Destineer      0.01      0.00   
16593  2002.0      Platform                  Kemco      0.01      0.00   
16594  2003.0       Shooter             Infogrames      0.01      0.00   
16595  2008.0        Racing             Activision      0.00      0.00   
16596  2010.0        Puzzle               7G//AMES      0.00      0.01   
16597  2003.0      Platform                Wanadoo      0.01      0.00   

       JP_Sales  Other_Sales  Global_Sales  
16588      0.00          0.0          0.01  
16589      0.01          0.0          0.01  
16590      0.01          0.0          0.01  
16591      0.00          0.0          0.01  
16592      0.00          0.0          0.01  
16593      0.00          0.0          0.01  
16594      0.00          0.0          0.01  
16595      0.00          0.0          0.01  
16596      0.00          0.0          0.01  
16597      0.00          0.0          0.01

'The top 3 platforms based on global sales are: '

Platform
PS2     1255.64
X360     979.96
PS3      957.84
Name: Global_Sales, dtype: float64

'The percentage of global sales for each genre is: '

Genre
Action          19.631094
Adventure        2.679688
Fighting         5.032375
Misc             9.079821
Platform         9.319832
Puzzle           2.745941
Racing           8.206322
Role-Playing    10.396012
Shooter         11.629135
Simulation       4.396644
Sports          14.920004
Strategy         1.963132
Name: Global_Sales, dtype: float64

'The correlation between NA_Sales and EU_Sales is: '

np.float64(0.767726748370264)

## Task 2 English-Spanish Dictionary
You are creating a basic English-Spanish dictionary that allows users to look up English words and find their Spanish translations.


### Tasks
* Create a dictionary where English words are keys and their Spanish translations are values.
* Ask the user to input an English word.
* Check if the word exists in the dictionary.
* If the word exists, print its Spanish translation.
* If the word does not exist, inform the user that the translation is not available.
* Implement a loop that allows the user to keep looking up words until they choose to exit.


In [3]:
my_dictionary = {
    "hello" : "hola",
    "goodbye" : "adios",
    "thank you" : "gracias",
    "please" : "por favor",
    "sorry" : "lo siento",
}

#loop till user exits
while True:
    user_input= input("Enter an English word or write exit: \n").lower()
    if user_input == "exit":
        break

    if user_input in my_dictionary:
        print("The Spanish translation of is: ", my_dictionary[user_input])
    else:
        print ("oops,this word doesnt exist\n")

The Spanish translation of is:  hola



## Task 3 Email Classification
Develope a tool which will classify an email.

### Tasks:
* Create a function classify_emails that takes a list of emails as an argument.
* Inside the function, categorize emails into "Important," "Promotions," and "Spam" based on keywords and content analysis.
* Loop through the emails and identify keywords to determine their category.
* If an email contains keywords indicating importance, assign it as "Important."
* If an email contains keywords related to promotions or deals, assign it as "Promotions."
* If an email is suspected to be spam based on certain keywords or patterns, assign it as "Spam."
* Return three lists of emails for each category.
* Print the lists.

In [4]:
email=['promotions','important','spam','more promotions','abit spam','very important','not important','aaahh promotions','hehe spam','promotions']
important_emails = []
spam_emails = []
promotion_emails = []
def classify_emails(emails):
    for i in emails:
        if 'important' in i:
            important_emails.append(i)
        elif 'spam' in i:
            spam_emails.append(i)
        elif 'promotions' in i:
            promotion_emails.append(i)

classify_emails(email)
print("The emails are: ", email)
print ("Important emails are: ", important_emails)
print ("Spam emails are: ", spam_emails)
print ("Other emails are: ", promotion_emails)


The emails are:  ['promotions', 'important', 'spam', 'more promotions', 'abit spam', 'very important', 'not important', 'aaahh promotions', 'hehe spam', 'promotions']
Important emails are:  ['important', 'very important', 'not important']
Spam emails are:  ['spam', 'abit spam', 'hehe spam']
Other emails are:  ['promotions', 'more promotions', 'aaahh promotions', 'promotions']


## Task 4 Online Store Shopping Cart
Write a Python program to simulate the online store's shopping cart system. The program should use a while loop to provide an interactive shopping experience.


### Tasks:
* Initialize an empty list called shopping_cart to store items.
* Display a welcome message and available products.
* Loop should be iterating over AI Response Simulator and Investment decision and keep asking for user input.
* Prompt the user to enter the number corresponding to the product they want to add to the cart.
* Check if the user entered 'q'. If so, break the loop.
* Convert the choice to an integer and validate it within the valid range (1 to 3).
* Based on the user's choice, add the selected product to the shopping_cart list.
* Display a confirmation message indicating the added product.
* Continue the loop to allow the user to add more products or proceed to checkout.
* After the loop ends, display the contents of the shopping cart.
* Display a goodbye message.
* End the program.

In [5]:
shopping_cart=[]

print ("WELCOME TO MODEST ATTIRE\n")
print ("We have the following items in stock: \n")
print ("1.Hijabs\n2.Abayas\n3.Jilbabs\n")

while True:
    user_input = input("Enter the number of the item you would like to purchase or 'q' to exit: \n")
    if user_input == "q":
        break

    if user_input == "1":
        shopping_cart.append("Hijab")
        print("Hijab has been added to your cart\n")
    elif user_input == "2":
        shopping_cart.append("Abaya")
        print("Abaya has been added to your cart\n")
    elif user_input == "3":
        shopping_cart.append("Jilbab")
        print("Jilbab has been added to your cart\n")
    else:
        print("Invalid input. Please enter a number from 1-3 or 'q' to exit\n")

print("Your shopping cart contains: ", shopping_cart)
print("Goodbyeee")

WELCOME TO MODEST ATTIRE

We have the following items in stock: 

1.Hijabs
2.Abayas
3.Jilbabs

Hijab has been added to your cart

Your shopping cart contains:  ['Hijab']
Goodbyeee


## Task 5
* Create two NumPy arrays of the same shape and perform element-wise addition on them.
* Calculate the element-wise product of two NumPy arrays.

In [6]:
import numpy as np

first_array = np.array((1, 2, 3, 4, 5))
second_array = np.array((6, 7, 8, 9, 10))
#sum
sum = first_array + second_array
print("The sum of the two arrays is: ", sum)

product = first_array * second_array
print("The product of the two arrays is: ", product)


The sum of the two arrays is:  [ 7  9 11 13 15]
The product of the two arrays is:  [ 6 14 24 36 50]


## Task 6
* Reshape a 1D NumPy array into a 2D array with dimensions (3, 4).

* Concatenate two NumPy arrays horizontally and vertically.

In [9]:
#1D TO 2D
import numpy as np
arr = np.array((1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12))
reshaped_arr = arr.reshape(3, 4)
print(reshaped_arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


## Task 7
* Reverse A List In Python Using Slicing


In [8]:
my_list= [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
#reverse
reversed_list = my_list[::-1]
print("The reversed list is: ", reversed_list)

The reversed list is:  [10, 9, 8, 7, 6, 5, 4, 3, 2, 1]


# TASK 8
You need to download the GitHub Desktop software, push your lab task to your GitHub account, and share the link on GCR as a submission.